site_name: Agrisemantics
theme: 'windmill'
repo_url: https://github.com/agrisemantics/website
repo_name: 'Github'
edit_uri: 'edit/master/docs/'
site_description: 'Agrisemantics home page'
dev_addr: '127.0.0.1:8080'
nav:
- Home : index.md
- GACS:
    - 'About GACS': GACShome.md
    - Guidelines:
        - 'Concepts': concepts.md
        - 'Concept relations': relations.md
        - 'Concept definitions': definitions.md
        - 'Concept labels': labels.md
        - 'Scientific and common names': names.md
        - 'Thematic classification': thematic_classification.md
        - 'Scope notes': scopenotes.md
    - 'Reference material': reference.md
- Agrisemantics WG:
    - 'About': agsem_about.md
    - 'Recommendations': agsem_recommendations.md
